from __future__ import annotations

from typing import Protocol

from apps.orchestrator.models.research import Brief, Run, RunEvent


class Conflict(Exception):
    pass


class RunRepository(Protocol):
    async def replay(self, brief: Brief, key: str, parent_id: str | None = None) -> Run | None: ...
    async def create(self, brief: Brief, key: str, parent_id: str | None = None) -> Run: ...
    async def get(self, run_id: str) -> Run | None: ...
    async def list(self, limit: int = 50) -> list[Run]: ...
    async def active(self) -> Run | None: ...
    async def save(self, run: Run) -> None: ...
    async def event(self, run_id: str, stage: str, message: str) -> None: ...
    async def events(self, run_id: str) -> list[RunEvent]: ...
