local all all trust
hostssl toir_runs,toir_runs_test toir_runs 0.0.0.0/0 scram-sha-256
host all toir_runs 0.0.0.0/0 reject
hostssl all toir_runs 0.0.0.0/0 reject
host all rag 127.0.0.1/32 scram-sha-256
host all rag 172.16.0.0/12 scram-sha-256
